Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from bs4 import BeautifulSoup
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service 
from webdriver_manager.chrome import ChromeDriverManager
## NOTE: Some users may want to try a Firefox Driver instead;
## Can comment above two lines and uncomment the below two lines
# from selenium.webdriver.firefox.service import Service
# from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select, WebDriverWait
import pandas as pd
import time
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mselenium[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwebdriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcommon[39;00m[38;5;21;01m.[39;00m[38;5;21;01mby[39;00m [38;5;28;01mimport[39;00m By
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mselenium[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwebdriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01mchrome[39;00m[38;5;21;01m.[39;00m[38;5;21;01mservice[39;00m [38;5;28;01mimport[39;00m Service 
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mwebdriver_manager[39;00m[38;5;21;01m.[39;00m[38;5;21;01mchrome[39;00m [38;5;28;01mimport[39;00m ChromeDriverManager
[1;32m      7[0m [38;5;66;03m## NOTE: Some users may want to try a Firefox Driver instead;[39;00m
[1;32m      8[0m [38;5;66;03m## Can comment above two lines and uncomment the below two lines[39;00m
[1;32m      9[0m [38;5;66;03m# from selenium.webdriver.firefox.service import Service[39;00m
[1;32m     10[0m [38;5;66;03m# from webdriver_manager.firefox import GeckoDriverManager[39;00m
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mselenium[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwebdriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01msupport[39;00m [38;5;28;01mimport[39;00m expected_conditions [38;5;28;01mas[39;00m EC

[0;31mModuleNotFoundError[0m: No module named 'webdriver_manager'
ModuleNotFoundError: No module named 'webdriver_manager'

