content/intro-to-python.ipynb:30002: [broken] http://localhost:8888: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81970a07f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
content/resources.md:6: [redirected with Found] https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/pandas_and_matplotlib.ipynb to https://nbviewer.org/github/QuantEcon/QuantEcon.notebooks/blob/master/pandas_and_matplotlib.ipynb
content/resources.md:5: [redirected with Found] https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/sci_python_quickstart.ipynb to https://nbviewer.org/github/QuantEcon/QuantEcon.notebooks/blob/master/sci_python_quickstart.ipynb
content/installation.md:21: [redirected permanently] https://urbanorg.box.com/s/3raiuvsykulh290884xkogduzbdhi371 to https://urbanorg.app.box.com/s/3raiuvsykulh290884xkogduzbdhi371
content/why-python.md:11: [redirected with Found] https://urbanorg.app.box.com/folder/162248420670 to https://urbanorg.account.box.com/login?redirect_url=%2Ffolder%2F162248420670
content/installation.md:13: [broken] https://www.anaconda.com/distribution/#download-section: Anchor 'download-section' not found
